Puppetfile
A bugfix in puppetlabs-apache 1.2.0 broke functionality in
puppet-horizon. The change was fixed in puppet-horizon 5.0.0 but is not
compatible with older versions of the apache module. This patch upgrades
the apache module to at least 1.2.
=> Pin apache to 1.2.x in Puppetfile

.travis.yml
This commit removes Ruby 1.8.7 and Puppet 2.7 from the TravisCI
configs. Since this module was never released with any CI it is safe to
remove these.
=> Fix travisCI issues

examples/multinode/10_setup_master.sh
When using ubuntu as the puppet master we don't need to worry about
iptables, but we should update apt before doing anything else.
=> Fix multinode deploy for ubuntu master

examples/multinode/Vagrantfile
The controller will fall over if only allowed 1G of memory. This commit
allows it 2G.
=> Give the multinode controller more memory

manifests/profile/ceilometer/api.pp
The new feature in #127 added support for services connecting as
different users, but did not change the ceilometer profile to set up
those users. This was a problem because services were unable to connect
as the users they were configured to use. This change adds that
support.
=> Fix ceilometer mongo user

Puppetfile, examples/allinone/Vagrantfile, examples/allinone/provision_manifests/base.pp, examples/multinode/Vagrantfile, examples/multinode/provision_manifests/base.pp, examples/swift/Vagrantfile, examples/swift/provision_manifests/base.pp, manifests/profile/rabbitmq.pp
nova::rabbitmq should be going away soon, so it is best to stop using
it. Moreover, the nova::rabbitmq class depends on an old version of the
rabbitmq module that contains what in some contexts is considered a
security vulnerability. While we can't change the rabbitmq version in
the metadata.json file because it will cause a conflict with the other
openstack modules, we can update our code and Puppetfile to use the
newer version and its new dependencies while maintaining compatibility
with the old version.
This commit also adds a host entry for localhost rabbitmq so that
rabbitmq can restart without being blocked by the firewall.
=> Rewrite the rabbitmq profile

examples/allinone.yaml, examples/common.yaml, manifests/common/nova.pp, manifests/config.pp, manifests/init.pp
glance api servers ipaddr may not always equal to the storage management address,
it might be virtual ipaddr instead of the static one under a HA configured environment.
=> Allow user to config `glance_api_servers` via hiera

Puppetfile
We updated the dependency in the metadata but not the Puppetfile.
This patch corrects the mistake.
=> Update mongodb Puppetfile dependency

manifests/profile/mongodb.pp
There was a bugfix in the 0.10.0 release of the mongodb module for
idempotency of the mongodb_user, but it only fixes the bug if using a
2.6 version of mongodb. This patch has the mongodb::globals class
manage the package repo so we can get a modern mongodb and take
advantage of the bugfix.
=> Have the mongodb module manage the mongo repo

Rakefile, manifests/profile/rabbitmq.pp
fail_on_warnings must be explicitly set to true in order to fail on
lint warnings instead of just errors.
=> Fix lint errors and error catching

manifests/resources/user.pp
Defaulting to add admin users to the heat_stack_owner role causes
problems if heat is not included in the deployment. This should be
managed somewhere else.
=> Remove heat_stack_owner from default admin roles

manifests/config.pp, manifests/init.pp, manifests/profile/horizon.pp
Using the `::horizon::fqdn` parameter causes the following warning:
```
(Scope(Class[Horizon])) Parameter fqdn is deprecated. Please use parameter allowed_hosts for setting ALLOWED_HOSTS in settings_local.py and parameter server_aliases for setting ServerAlias directives in vhost.conf.
```
The hard-coded list of hosts also prevents the use of a service virtual host name (i.e. you have to connect to the dashboard using the hostname).
This PR replaces the use of `::horizon::fqdn` with `::horizon::allowed_hosts` and `::horizon::server_aliases` in `openstack::profile::horizon`.
It also introduces 2 new hiera parameters: `openstack::horizon::allowed_hosts` and `openstack::horizon::server_aliases`, which allowes the corresponding parameters to be extended (i.e. to allow the use of service …
=> Use ::horizon::allow_hosts and ::horizon::server_aliases instead of ::horizon::fqdn

examples/swift/site.pp
PuppetDB is required to run swift, so make sure it's installed in the
example.
=> Use puppetdb in swift example

examples/allinone/30_deploy.sh, examples/allinone/Vagrantfile, examples/multinode/30_deploy_control.sh, examples/multinode/40_deploy_nodes.sh, examples/multinode/Vagrantfile, examples/swift/25_deploy_swiftstore.sh, examples/swift/30_deploy_control.sh, examples/swift/Vagrantfile
The Puppet Labs has multiple providers, so it is more accessible for
trying out the examples.
We're pinning the version to 1.0.0 because 1.0.1 seems to have issues
with its networking interfaces.
Additionally, this vagrant box comes with firewalld enabled and many
firewall rules. Firewalld responds to iptables-save which confuses the
firewall iptables provider and causes errors on the first round of
puppet runs, even if disabling firewalld is puppet's first change.
Because of this, we add a command to the deployment script to stop
firewalld before running puppet so that puppet succeeds on the first
run.
=> Use Puppet Labs CentOS 7 vagrant box in examples

manifests/common/keystone.pp, manifests/common/neutron.pp, manifests/config.pp, manifests/init.pp, manifests/profile/keystone.pp, manifests/role/allinone.pp
Currently this module only supports using the default eventlet-based
web server for API services. This is only sustainable in a production
environment if using another web proxy in front of it, which is not
included in this module. This patch adds the ability to turn on the
keystone::wsgi::apache class and use the keystone API with Apache.
Other notes:
- SSL is hard-coded to be turned off, since this module doesn't
support SSL yet. We will fix this later.
- Since the neutron::server::notifications class was not contained in
the openstack::common::neutron class, the
nova_admin_tenant_id_setter may try to authenticate against the
keystone API before the HTTP service is turned on. We contain it
within the openstack::common::neutron class with anchors so that the
ordering of the profile …
=> Enable apache/wsgi setup for keystone API

manifests/common/ml2.pp, manifests/common/ml2/ovs.pp, manifests/profile/neutron/agent.pp, manifests/profile/neutron/router.pp, manifests/profile/neutron/server.pp
Without this patch, the neutron::agents::ml2::ovs class was bundled
into the openstack::common::ovs class, which was included in the
neutron server profile. Since the OVS agent is not required to run on
the neutron server, include it only where it's actually needed.
Closes #107
=> Don't require that OVS agent run on neutron server

manifests/profile/rabbitmq.pp, manifests/resources/repo.pp, manifests/resources/repo/epel.pp, manifests/resources/repo/erlang.pp, manifests/resources/repo/rdo.pp, manifests/resources/repo/yum_refresh.pp, metadata.json
Two commits here that fix deployments on Fedora 20 and 21:
1) Puppet was failing to add the erlang-solutions repo because Erlang doesn't provide a repo for newer versions of Fedora. Fixed by not requiring that repo on Fedora since the Fedora repos have new enough erlang.
2) A syntax issue was causing Puppet to fail trying to require the yum_refresh exec when that class wasn't included on Fedora. Fixed by reorganizing yum_refresh elements to make a little more sense.
Last commit formalizes support for Fedora in the metadata.
=> Fix fedora

manifests/profile/firewall.pp
The firewall module takes care of this for us. Moreover, the fact
is operatingsystemmajrelease, not operatingsystemmajversion, so this
was never being applied.
=> Remove iptables-services package resource

manifests/profile/firewall/pre.pp
Profiles should be self-contained as much as possible. Removing the
dependency relationship between the firewallchain resources and the
repository classes causes no ill effects, plus it simplifies the code
because it is no longer conditional on osfamily.
=> Remove class dependencies from firewall profile

manifests/profile/nova/compute.pp
Nova images won't boot with the version of device-mapper installed by
default on RedHat. We need to make sure we have the latest available
version, and it needs to refresh the libvirt and then the nova-compute
service after being updated.
=> Ensure device mapper package is latest

Puppetfile, metadata.json
The stackforge/puppet-openstacklib module has updated its dependency on
puppetlabs-mysql to 3.x [1]. We do not need to have puppetlabs-mysql as
a dependency of this module as all the stackforge modules will pull
puppet-openstacklib in as a dependency, which pulls in
puppetlabs-mysql as a dependency.
This commit also pins puppetlabs-mysql to a stable 3.x branch in the
Puppetfile.
[1] https://review.openstack.org/#/c/149508/
Closes #187
=> Fix puppetlabs/mysql dependency

metadata.json
RDO only makes juno (and soon to be kilo) packages for RHEL 7, so
listing RedHat 6 as a supported operating system was a mistake.
Closes #189
=> Remove RedHat 6 from supported operating systems

lib/puppet/parser/functions/ip_for_network.rb
I have a custom fact named "ipaddress_range" which was causing the ip_for_network function to bomb. This is a proposed fix which takes the list of interfaces and then looks up each IP address for the interfaces explicitly.
=> Fix for ip_for_network

README.md
We need a more productive way to help people than the GitHub issues
tracker for this module. This README addition seeks to direct new users
to the most appropriate source of help and the correct bug tracker.
=> Add a getting help guide
